---
deployment:
  tasks:
    # Nobitex Laravel application (outside public_html)
    - export LARAVELPATH=/home/fmtsnwvt/nobitex-panel/
    - /bin/cp -R app $LARAVELPATH
    - /bin/cp -R bootstrap $LARAVELPATH
    - /bin/cp -R config $LARAVELPATH
    - /bin/cp -R database $LARAVELPATH
    - /bin/cp -R resources $LARAVELPATH
    - /bin/cp -R routes $LARAVELPATH
    - /bin/cp -R storage $LARAVELPATH
    - /bin/cp artisan $LARAVELPATH
    - /bin/cp composer.json $LARAVELPATH
    - /bin/cp composer.lock $LARAVELPATH

    # Laravel public directory -> subdomain document root
    - export PUBLICPATH=/home/fmtsnwvt/nobitex-panel/public/
    - /bin/cp -R public/. $PUBLICPATH
